version: 2
defaults:
  working_directory: ~/repo
  docker: &ref_0
    - image: circleci/node:14.15.4
jobs:
  core:
    working_directory: ~/repo
    docker: *ref_0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - run: npm run test
      - persist_to_workspace:
          root: ~/repo
          paths: .
workflows:
  version: 2
  core:
    jobs:
      - core:
          filters:
            branches:
              only:
                - master
          parallelism: 2
